In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
a[1]

np.int64(2)

In [4]:
a[:2]

array([1, 2])

In [5]:
a[2:]


array([3, 4, 5, 6, 7, 8])

In [6]:
multidim_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
multidim_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
no_of_rows = multidim_array.shape[0]
no_of_cols = multidim_array.shape[1]
no_of_rows, no_of_cols

(3, 3)

In [8]:
multidim_array.ndim

2

In [9]:
three_dim_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
three_dim_array

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [10]:
print("No of dimnsions -", three_dim_array.ndim)
print("Shape -", three_dim_array.shape)
print("Size -", three_dim_array.size)
print("Data Type -", three_dim_array.dtype)
print("Length of shape -", len(three_dim_array.shape))


No of dimnsions - 3
Shape - (3, 2, 3)
Size - 18
Data Type - int64
Length of shape - 3


In [11]:
three_dim_array = np.array([
    [[1, 2, 3], [4, 5, 6]],        # 1st block
    [[7, 8, 9], [10, 11, 12]],     # 2nd block
    [[13, 14, 15], [16, 17, 18]]   # 3rd block
])
print("Shape -", three_dim_array.shape)
"""
Count the nesting

Outermost list → has 3 elements (each is a “block”).
Each block → has 2 sub-lists.
Each sub-list → has 3 numbers.

So the structure is:
3 blocks
each with 2 rows
each row has 3 columns

Shape = (3, 2, 3)
"""

Shape - (3, 2, 3)


'\nCount the nesting\n\nOutermost list → has 3 elements (each is a “block”).\nEach block → has 2 sub-lists.\nEach sub-list → has 3 numbers.\n\nSo the structure is:\n3 blocks\neach with 2 rows\neach row has 3 columns\n\nShape = (3, 2, 3)\n'

In [12]:
np.zeros((2,5)) # Row of 2 and Column of 5 with all values as 0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
# Fill with single value 
np.full((2,5), 9) # Row of 2 and Column of 5 with all values as 9

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [14]:
# Create am empty array
one_dim_array = np.empty(3)

# For multi dimensional array
two_dim_array = np.empty((2,3))
print("One Dim Array -", one_dim_array)
print("Two Dim Array -", two_dim_array)


One Dim Array - [1.93101617e-312 1.97345609e-312 1.21885047e-289]
Two Dim Array - [[-9.23910446e-312 -7.36776665e+142  9.23910423e-312]
 [ 9.23910423e-312  4.94065646e-323  2.37151510e-322]]


In [15]:
# Sorting
unsorted_array = np.array([3, 7, 1, 9, 4, 2, 8, 5, 6])
print("Before Sorting -", unsorted_array)
print("After Sorting -", np.sort(unsorted_array))

# Find the index of sorted array
print("Index of Sorted Array -", np.argsort(unsorted_array))

Before Sorting - [3 7 1 9 4 2 8 5 6]
After Sorting - [1 2 3 4 5 6 7 8 9]
Index of Sorted Array - [2 5 0 4 7 8 1 6 3]


In [16]:
# Concatenate two arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
final_array =np.concatenate((array1, array2))
print("Final Array -", final_array)

Final Array - [1 2 3 4 5 6]


In [17]:
# Reshape the array
reshaped_array_1 = final_array.reshape((2, 3))
reshaped_array_2 = final_array.reshape((3, 2))
print("Reshaped Array 1 -\n", reshaped_array_1)
print("Reshaped Array 2 -\n", reshaped_array_2)

Reshaped Array 1 -
 [[1 2 3]
 [4 5 6]]
Reshaped Array 2 -
 [[1 2]
 [3 4]
 [5 6]]


In [18]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
reshaped_array = array1.reshape((2, 3))
reshaped_array

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Creatte array with range
range_array1 = np.arange(10)
range_array2 = np.arange(1, 10, 2) # Start, End, Step
range_array1, range_array2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [20]:
array1 = np.array([1,2,3,4,5,6,7,8])
print("Shape before adding new axis -", array1.shape)

Shape before adding new axis - (8,)


In [21]:
# Add new axis in the array
new_axis_array = array1[np.newaxis, :]
print("Shape after adding new axis -", new_axis_array.shape)

Shape after adding new axis - (1, 8)


In [22]:
# Check both array dimensions
print("Original array dimensions:", array1.ndim)
print("New axis array dimensions:", new_axis_array.ndim)

Original array dimensions: 1
New axis array dimensions: 2


In [23]:
# Indexing and slicing
array_1 = np.array([1,2,3,7,5,9])

In [24]:
# Flatten the array
flattened_array = array_1.flatten()
flattened_array

array([1, 2, 3, 7, 5, 9])

In [25]:
# Different slicing
sliced_array1 = array_1[2:5]  # Elements from index 2 to 4
sliced_array2 = array_1[:4]   # First four elements
sliced_array3 = array_1[::2]  # Every second element
sliced_array4 = array_1[-3:]  # Last three elements
sliced_array5 = array_1[::-1]  # Reversed array
sliced_array6 = array_1[3:]

sliced_array1, sliced_array2, sliced_array3, sliced_array4, sliced_array5, sliced_array6

(array([3, 7, 5]),
 array([1, 2, 3, 7]),
 array([1, 3, 5]),
 array([7, 5, 9]),
 array([9, 5, 7, 3, 2, 1]),
 array([7, 5, 9]))

In [26]:
# Condition based slicing
array_1 = np.array([[1,2,3], [4,5,6], [5,8,9]])
condition = array_1 > 5
condition

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

In [27]:
array_1[condition] 

array([6, 8, 9])

In [28]:
array_1 = np.array([[1,7,5], [5,8,4]])
array_2 = np.array([[2,6,5], [7,3,4]])
print("Array 1 -\n", array_1)
print("Array 2 -\n", array_2)

Array 1 -
 [[1 7 5]
 [5 8 4]]
Array 2 -
 [[2 6 5]
 [7 3 4]]


In [29]:
# Vertical Stack (It add rows)
vstack_array = np.vstack((array_1, array_2))
vstack_array

array([[1, 7, 5],
       [5, 8, 4],
       [2, 6, 5],
       [7, 3, 4]])

In [30]:
# Horizontal Stack (It add columns)
hstack_array = np.hstack((array_1, array_2))
hstack_array

array([[1, 7, 5, 2, 6, 5],
       [5, 8, 4, 7, 3, 4]])

In [31]:
# Range array
range_array = np.arange(1, 21).reshape((5, 4))
range_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [32]:
# Split into equal shaped
"""
In this whatever the range array columns, must be divisible by n where n is the number of arrays you want to split into. 
"""
split_array = np.hsplit(range_array, 2)
split_array

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [15, 16],
        [19, 20]])]

In [33]:
array_1 = np.array([1,2,3,4,5,6])
print("Original Array -", array_1)
array_1[3] = 25
print("Changed Array -", array_1)

Original Array - [1 2 3 4 5 6]
Changed Array - [ 1  2  3 25  5  6]


In [34]:
# Deep Copy
array_2 = np.array([1,2,3,4,5,6])
print("Original Array Before Change -", array_2)
deep_copied_array = array_2.copy()
deep_copied_array[0] = 100
print("Original Array After Change -", array_2)
print("Changed Array -", deep_copied_array)

Original Array Before Change - [1 2 3 4 5 6]
Original Array After Change - [1 2 3 4 5 6]
Changed Array - [100   2   3   4   5   6]


In [35]:
# basic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition -", a + b)
print("Subtraction -", b - a)
print("Multiplication -", a * b)
print("Division -", b / a)
print("Square -", a ** 2)
print("Square Root -", np.sqrt(b))
print("Mean -", np.mean(a))
print("Standard Deviation -", np.std(a))
print("Max -", np.max(a))
print("Min -", np.min(a))
print("Sum -", np.sum(a))
print("Dot Product -", np.dot(a, b))
print("Product -", np.prod(a))

Addition - [5 7 9]
Subtraction - [3 3 3]
Multiplication - [ 4 10 18]
Division - [4.  2.5 2. ]
Square - [1 4 9]
Square Root - [2.         2.23606798 2.44948974]
Mean - 2.0
Standard Deviation - 0.816496580927726
Max - 3
Min - 1
Sum - 6
Dot Product - 32
Product - 6


In [36]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Transpose Matrix -\n", np.transpose(array))

# Transpose with shortcut
print("Transpose Matrix -\n", array.T)

Transpose Matrix -
 [[1 4]
 [2 5]
 [3 6]]
Transpose Matrix -
 [[1 4]
 [2 5]
 [3 6]]


In [37]:
arr_with_duplicates = np.array([1,3,4,6,7,3,4,5,8,2,1,5])
unique_elements = np.unique(arr_with_duplicates)
unique_elements

array([1, 2, 3, 4, 5, 6, 7, 8])

In [38]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array -\n", array_2d)

reversed_array = np.flip(array_2d)
print("Reversed Array -\n", reversed_array)

reversed_arr_rows = np.flipud(array_2d)
print("Reversed Array Rows -\n", reversed_arr_rows)

reversed_arr_cols = np.fliplr(array_2d)
print("Reversed Array Columns -\n", reversed_arr_cols)

Original Array -
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed Array -
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Reversed Array Rows -
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed Array Columns -
 [[3 2 1]
 [6 5 4]
 [9 8 7]]


In [39]:
""" Different ways to flatten an array 
flatten -> It returns a copy of new array. It does not affect the original array.
ravel -> It directly changes the original array and returns a flattened view of the original array.
"""
flattened_array_1 = array_2d.flatten()
print("Flattened Array -", flattened_array_1)

flattened_array_2 = array_2d.ravel()
print("Flattened Array (Ravel) -", flattened_array_2)

Flattened Array - [1 2 3 4 5 6 7 8 9]
Flattened Array (Ravel) - [1 2 3 4 5 6 7 8 9]


In [40]:
new_array = np.array([1,2,3,4,5,6,7,8,9])
condition_array = new_array > 5
new_array = np.where(condition_array, new_array**2, new_array)
new_array

"""
it expression is same as below
for i in range(len(new_array)):
    if new_array[i] > 5:
        new_array[i] = new_array[i] ** 2
    else:
        new_array[i] = new_array[i]
"""


'\nit expression is same as below\nfor i in range(len(new_array)):\n    if new_array[i] > 5:\n        new_array[i] = new_array[i] ** 2\n    else:\n        new_array[i] = new_array[i]\n'

In [41]:
# Array compatibility
array_1 = np.array([[1, 2, 3], [4, 5, 6]])
array_2 = np.array([[7, 8, 9], [10, 11, 12]])
array_3 = np.array([[1, 2], [3, 4], [5, 6]])

print("Compatibility shape -", array_1.shape == array_2.shape)
print("Compatibility shape -", array_1.shape == array_3.shape)

Compatibility shape - True
Compatibility shape - False


In [42]:
# Delete operation
array_1d = np.array([1,2,3,4,5,6,7,8,9])

deleted_array_1 = np.delete(array_1d, 2)
print("Array after deletion -", deleted_array_1)

deleted_array_2 = np.delete(array_1d, [2,5]) # Delete index 2 and 5
print("Array after deletion -", deleted_array_2)


Array after deletion - [1 2 4 5 6 7 8 9]
Array after deletion - [1 2 4 5 7 8 9]


In [43]:
boolean_format_result = np.where(condition_array, True, False)
boolean_format_result

array([False, False, False, False, False,  True,  True,  True,  True])

In [44]:
# Array broadcasting
array_1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2 = np.array([1, 0, 1])
result_array = array_1 + array_2
result_array

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

# Practise with sample data

In [ ]:
# Data Structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [101, 2500, 2700, 3000, 3200],  
    [102, 1500, 1600, 1550, 1650],
    [103, 1800, 1850, 1900, 1950],
    [104, 3200, 3100, 3400, 3500],  
    [105, 5000, 5200, 5100, 5400],
    [106, 2500, 2400, 2300, 2200],
    [107, 1800, 1900, 2100, 2500],
])
sales_data

array([[ 101, 2500, 2700, 3000, 3200],
       [ 102, 1500, 1600, 1550, 1650],
       [ 103, 1800, 1850, 1900, 1950],
       [ 104, 3200, 3100, 3400, 3500],
       [ 105, 5000, 5200, 5100, 5400],
       [ 106, 2500, 2400, 2300, 2200],
       [ 107, 1800, 1900, 2100, 2500]])

In [46]:
# sales data shape
sales_data.shape

# First 3 row data
print("First 3 rows data -\n", sales_data[:3])

First 3 rows data -
 [[ 101 2500 2700 3000 3200]
 [ 102 1500 1600 1550 1650]
 [ 103 1800 1850 1900 1950]]


In [47]:
# Total sales calculation
total_sales = np.sum(sales_data[:, 1:], axis=1)
total_sales

array([11400,  6300,  7500, 13200, 20700,  9400,  8300])

## More Array Creation Methods

In [48]:
# np.ones - Create array filled with ones
ones_array = np.ones((3, 4))
print("Ones array:")
print(ones_array)

# np.linspace - Create evenly spaced numbers
linspace_array = np.linspace(0, 10, 5)  # 5 numbers from 0 to 10
print("\nLinspace array (0 to 10, 5 points):", linspace_array)

# np.logspace - Create logarithmically spaced numbers
logspace_array = np.logspace(0, 2, 5)  # 5 numbers from 10^0 to 10^2
print("Logspace array (10^0 to 10^2, 5 points):", logspace_array)


Ones array:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Linspace array (0 to 10, 5 points): [ 0.   2.5  5.   7.5 10. ]
Logspace array (10^0 to 10^2, 5 points): [  1.           3.16227766  10.          31.6227766  100.        ]


## Random Arrays


In [49]:
# Random arrays
print("Random float array (0 to 1):")
random_float = np.random.rand(3, 3)
print(random_float)

print("\nRandom normal distribution (mean=0, std=1):")
random_normal = np.random.randn(3, 3)
print(random_normal)

print("\nRandom integers (1 to 10):")
random_int = np.random.randint(1, 11, size=(3, 3))
print(random_int)

print("\nRandom choice from array:")
choices = np.array([1, 5, 10, 15, 20])
random_choice = np.random.choice(choices, size=5)
print("Choices:", choices)
print("Random selection:", random_choice)


Random float array (0 to 1):
[[0.94697227 0.14377435 0.47858019]
 [0.83360579 0.41283829 0.30248091]
 [0.88866495 0.96077427 0.59339541]]

Random normal distribution (mean=0, std=1):
[[ 0.8084583  -0.28365924 -0.56534196]
 [-0.57745963 -0.55584371 -0.63200924]
 [ 1.58523154 -0.23300492  0.82778404]]

Random integers (1 to 10):
[[1 7 1]
 [1 7 3]
 [6 8 3]]

Random choice from array:
Choices: [ 1  5 10 15 20]
Random selection: [15 20  5  5 20]


## Data Type Conversions


In [50]:
# Data type conversions
arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)
print("Original dtype:", arr.dtype)

# Convert to different data types
arr_float = arr.astype(float)
print("\nConverted to float:", arr_float)
print("Float dtype:", arr_float.dtype)

arr_complex = arr.astype(complex)
print("\nConverted to complex:", arr_complex)
print("Complex dtype:", arr_complex.dtype)

arr_bool = arr.astype(bool)
print("\nConverted to bool:", arr_bool)
print("Bool dtype:", arr_bool.dtype)

# String conversion
arr_str = arr.astype(str)
print("\nConverted to string:", arr_str)
print("String dtype:", arr_str.dtype)


Original array: [1 2 3 4 5]
Original dtype: int64

Converted to float: [1. 2. 3. 4. 5.]
Float dtype: float64

Converted to complex: [1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]
Complex dtype: complex128

Converted to bool: [ True  True  True  True  True]
Bool dtype: bool

Converted to string: ['1' '2' '3' '4' '5']
String dtype: <U21


## Advanced Indexing


In [51]:
# Advanced indexing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array:")
print(arr)

# Fancy indexing with lists
print("\nFancy indexing - specific elements:")
fancy_result = arr[[0, 2], [1, 3]]  # Elements at (0,1) and (2,3)
print(fancy_result)

# Boolean indexing
print("\nBoolean indexing - elements > 5:")
bool_mask = arr > 5
print("Boolean mask:")
print(bool_mask)
print("Elements > 5:", arr[bool_mask])

# np.where for conditional selection
print("\nnp.where - replace values > 7 with -1:")
result = np.where(arr > 7, -1, arr)
print(result)

# np.take - extract elements by index
print("\nnp.take - extract elements at indices [0, 5, 8]:")
taken = np.take(arr, [0, 5, 8])
print(taken)

# np.compress - extract elements based on condition
print("\nnp.compress - extract elements > 6:")
# compressed = np.compress(arr > 6, arr)
compressed = np.compress((arr > 6).ravel(), arr.ravel())
print(compressed)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Fancy indexing - specific elements:
[ 2 12]

Boolean indexing - elements > 5:
Boolean mask:
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
Elements > 5: [ 6  7  8  9 10 11 12]

np.where - replace values > 7 with -1:
[[ 1  2  3  4]
 [ 5  6  7 -1]
 [-1 -1 -1 -1]]

np.take - extract elements at indices [0, 5, 8]:
[1 6 9]

np.compress - extract elements > 6:
[ 7  8  9 10 11 12]


## More Reshaping Operations


In [52]:
# More reshaping operations
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original array:")
print(arr)

# ravel vs flatten
print("\nravel (view):")
raveled = arr.ravel()
print(raveled)
print("Is raveled a view?", raveled.base is not None)

print("\nflatten (copy):")
flattened = arr.flatten()
print(flattened)
print("Is flattened a view?", flattened.base is not None)

# resize (modifies original array)
print("\nresize (modifies original):")
arr_resize = arr.copy()
arr_resize.resize((3, 2))
print("After resize to (3,2):")
print(arr_resize)

# Different transpose methods
print("\nTranspose methods:")
print("Original shape:", arr.shape)
print("arr.T shape:", arr.T.shape)
print("np.transpose shape:", np.transpose(arr).shape)
print("np.swapaxes(0,1) shape:", np.swapaxes(arr, 0, 1).shape)

# moveaxis
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D array shape:", arr_3d.shape)
print("moveaxis(0, 2) shape:", np.moveaxis(arr_3d, 0, 2).shape)


Original array:
[[1 2 3]
 [4 5 6]]

ravel (view):
[1 2 3 4 5 6]
Is raveled a view? True

flatten (copy):
[1 2 3 4 5 6]
Is flattened a view? False

resize (modifies original):
After resize to (3,2):
[[1 2]
 [3 4]
 [5 6]]

Transpose methods:
Original shape: (2, 3)
arr.T shape: (3, 2)
np.transpose shape: (3, 2)
np.swapaxes(0,1) shape: (3, 2)

3D array shape: (2, 2, 2)
moveaxis(0, 2) shape: (2, 2, 2)


## More Stacking and Splitting


In [53]:
# More stacking and splitting operations
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)

# Different stacking methods
print("\nStacking methods:")
print("hstack (horizontal):")
print(np.hstack((arr1, arr2)))

print("\nvstack (vertical):")
print(np.vstack((arr1, arr2)))

print("\ndstack (depth):")
print(np.dstack((arr1, arr2)))

print("\nconcatenate (axis=0):")
print(np.concatenate((arr1, arr2), axis=0))

print("\nconcatenate (axis=1):")
print(np.concatenate((arr1, arr2), axis=1))

print("\ncolumn_stack:")
print(np.column_stack((arr1, arr2)))

print("\nrow_stack:")
print(np.row_stack((arr1, arr2)))

# Splitting operations
arr_large = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\nLarge array for splitting:")
print(arr_large)

print("\nSplitting methods:")
print("split (equal parts):")
split_result = np.split(arr_large, 2, axis=1)
for i, part in enumerate(split_result):
    print(f"Part {i+1}:")
    print(part)

print("\narray_split (unequal parts):")
array_split_result = np.array_split(arr_large, 3, axis=1)
for i, part in enumerate(array_split_result):
    print(f"Part {i+1}:")
    print(part)

print("\nhsplit:")
hsplit_result = np.hsplit(arr_large, 2)
for i, part in enumerate(hsplit_result):
    print(f"Part {i+1}:")
    print(part)

print("\nvsplit:")
vsplit_result = np.vsplit(arr_large, 3)
for i, part in enumerate(vsplit_result):
    print(f"Part {i+1}:")
    print(part)


Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Stacking methods:
hstack (horizontal):
[[1 2 5 6]
 [3 4 7 8]]

vstack (vertical):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

dstack (depth):
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

concatenate (axis=0):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate (axis=1):
[[1 2 5 6]
 [3 4 7 8]]

column_stack:
[[1 2 5 6]
 [3 4 7 8]]

row_stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Large array for splitting:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Splitting methods:
split (equal parts):
Part 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2:
[[ 3  4]
 [ 7  8]
 [11 12]]

array_split (unequal parts):
Part 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2:
[[ 3]
 [ 7]
 [11]]
Part 3:
[[ 4]
 [ 8]
 [12]]

hsplit:
Part 1:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Part 2:
[[ 3  4]
 [ 7  8]
 [11 12]]

vsplit:
Part 1:
[[1 2 3 4]]
Part 2:
[[5 6 7 8]]
Part 3:
[[ 9 10 11 12]]


C:\Users\Sumit Amit\AppData\Local\Temp\ipykernel_6696\561705946.py:30: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack((arr1, arr2)))


## Universal Functions (ufuncs)


In [54]:
# Universal Functions (ufuncs)
arr = np.array([0, np.pi/4, np.pi/2, np.pi])
print("Original array (in radians):", arr)

# Trigonometric functions
print("\nTrigonometric functions:")
print("sin:", np.sin(arr))
print("cos:", np.cos(arr))
print("tan:", np.tan(arr))

# Inverse trigonometric functions
print("\nInverse trigonometric functions:")
print("arcsin:", np.arcsin(np.array([0, 0.5, 1])))
print("arccos:", np.arccos(np.array([0, 0.5, 1])))
print("arctan:", np.arctan(np.array([0, 1, np.sqrt(3)])))

# Exponential and logarithmic functions
print("\nExponential and logarithmic functions:")
arr_exp = np.array([0, 1, 2, 3])
print("exp:", np.exp(arr_exp))
print("log:", np.log(arr_exp[1:]))  # Skip 0 to avoid log(0)
print("log10:", np.log10(np.array([1, 10, 100])))
print("log2:", np.log2(np.array([1, 2, 4, 8])))

# Rounding functions
print("\nRounding functions:")
arr_float = np.array([1.2, 1.7, -1.2, -1.7])
print("Original:", arr_float)
print("around:", np.around(arr_float))
print("floor:", np.floor(arr_float))
print("ceil:", np.ceil(arr_float))
print("trunc:", np.trunc(arr_float))

# Absolute and square root functions
print("\nAbsolute and square root functions:")
arr_abs = np.array([-4, -1, 0, 1, 4])
print("Original:", arr_abs)
print("abs:", np.abs(arr_abs))
print("sqrt:", np.sqrt(np.abs(arr_abs)))
print("square:", np.square(arr_abs))


Original array (in radians): [0.         0.78539816 1.57079633 3.14159265]

Trigonometric functions:
sin: [0.00000000e+00 7.07106781e-01 1.00000000e+00 1.22464680e-16]
cos: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -1.00000000e+00]
tan: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.22464680e-16]

Inverse trigonometric functions:
arcsin: [0.         0.52359878 1.57079633]
arccos: [1.57079633 1.04719755 0.        ]
arctan: [0.         0.78539816 1.04719755]

Exponential and logarithmic functions:
exp: [ 1.          2.71828183  7.3890561  20.08553692]
log: [0.         0.69314718 1.09861229]
log10: [0. 1. 2.]
log2: [0. 1. 2. 3.]

Rounding functions:
Original: [ 1.2  1.7 -1.2 -1.7]
around: [ 1.  2. -1. -2.]
floor: [ 1.  1. -2. -2.]
ceil: [ 2.  2. -1. -1.]
trunc: [ 1.  1. -1. -1.]

Absolute and square root functions:
Original: [-4 -1  0  1  4]
abs: [4 1 0 1 4]
sqrt: [2. 1. 0. 1. 2.]
square: [16  1  0  1 16]


## Linear Algebra Operations


In [55]:
# Linear Algebra Operations
# Create matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
v = np.array([1, 2])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nVector v:")
print(v)

# Dot product and matrix multiplication
print("\nDot product and matrix multiplication:")
print("A @ B (matrix multiplication):")
print(A @ B)

print("\nnp.dot(A, B):")
print(np.dot(A, B))

print("\nnp.matmul(A, B):")
print(np.matmul(A, B))

# Inner and outer products
print("\nInner and outer products:")
print("Inner product of v with itself:", np.inner(v, v))
print("Outer product of v with itself:")
print(np.outer(v, v))

# Determinant and inverse
print("\nDeterminant and inverse:")
det_A = np.linalg.det(A)
print(f"Determinant of A: {det_A}")

if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:")
    print(inv_A)
    
    # Verify: A * A^(-1) = I
    identity_check = A @ inv_A
    print("A * A^(-1) (should be identity):")
    print(identity_check)

# Eigenvalues and eigenvectors
print("\nEigenvalues and eigenvectors:")
eigenvals, eigenvecs = np.linalg.eig(A)
print("Eigenvalues:", eigenvals)
print("Eigenvectors:")
print(eigenvecs)

# Solve linear equations Ax = b
print("\nSolve linear equations Ax = b:")
b = np.array([5, 11])
x = np.linalg.solve(A, b)
print(f"b = {b}")
print(f"Solution x = {x}")
print(f"Verification: A @ x = {A @ x}")

# Matrix norms
print("\nMatrix norms:")
print("Frobenius norm of A:", np.linalg.norm(A, 'fro'))
print("L2 norm of A:", np.linalg.norm(A, 2))
print("L1 norm of A:", np.linalg.norm(A, 1))
print("Infinity norm of A:", np.linalg.norm(A, np.inf))


Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Vector v:
[1 2]

Dot product and matrix multiplication:
A @ B (matrix multiplication):
[[19 22]
 [43 50]]

np.dot(A, B):
[[19 22]
 [43 50]]

np.matmul(A, B):
[[19 22]
 [43 50]]

Inner and outer products:
Inner product of v with itself: 5
Outer product of v with itself:
[[1 2]
 [2 4]]

Determinant and inverse:
Determinant of A: -2.0000000000000004
Inverse of A:
[[-2.   1. ]
 [ 1.5 -0.5]]
A * A^(-1) (should be identity):
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]

Eigenvalues and eigenvectors:
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

Solve linear equations Ax = b:
b = [ 5 11]
Solution x = [1. 2.]
Verification: A @ x = [ 5. 11.]

Matrix norms:
Frobenius norm of A: 5.477225575051661
L2 norm of A: 5.464985704219043
L1 norm of A: 6.0
Infinity norm of A: 7.0


## Statistics Functions


In [56]:
# Statistics Functions
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Data:", data)

# Basic statistics
print("\nBasic statistics:")
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard deviation:", np.std(data))
print("Variance:", np.var(data))
print("Min:", np.min(data))
print("Max:", np.max(data))
print("Sum:", np.sum(data))
print("Product:", np.prod(data))

# Percentiles and quantiles
print("\nPercentiles and quantiles:")
print("25th percentile:", np.percentile(data, 25))
print("50th percentile (median):", np.percentile(data, 50))
print("75th percentile:", np.percentile(data, 75))
print("90th percentile:", np.percentile(data, 90))

# Quantiles (same as percentiles but in 0-1 range)
print("\nQuantiles:")
print("0.25 quantile:", np.quantile(data, 0.25))
print("0.5 quantile:", np.quantile(data, 0.5))
print("0.75 quantile:", np.quantile(data, 0.75))

# Correlation and covariance
print("\nCorrelation and covariance:")
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print("Data x:", x)
print("Data y:", y)
print("Correlation coefficient:", np.corrcoef(x, y)[0, 1])
print("Covariance matrix:")
print(np.cov(x, y))

# Mode (requires scipy.stats)
try:
    from scipy import stats
    data_with_mode = np.array([1, 2, 2, 3, 3, 3, 4, 5])
    mode_result = stats.mode(data_with_mode)
    print(f"\nMode of {data_with_mode}: {mode_result.mode[0]} (appears {mode_result.count[0]} times)")
except ImportError:
    print("\nMode calculation requires scipy.stats (not available)")

# Cumulative functions
print("\nCumulative functions:")
print("Cumulative sum:", np.cumsum(data))
print("Cumulative product:", np.cumprod(data[:5]))  # Use smaller array for product


Data: [ 1  2  3  4  5  6  7  8  9 10]

Basic statistics:
Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25
Min: 1
Max: 10
Sum: 55
Product: 3628800

Percentiles and quantiles:
25th percentile: 3.25
50th percentile (median): 5.5
75th percentile: 7.75
90th percentile: 9.1

Quantiles:
0.25 quantile: 3.25
0.5 quantile: 5.5
0.75 quantile: 7.75

Correlation and covariance:
Data x: [1 2 3 4 5]
Data y: [ 2  4  6  8 10]
Correlation coefficient: 0.9999999999999999
Covariance matrix:
[[ 2.5  5. ]
 [ 5.  10. ]]

Mode calculation requires scipy.stats (not available)

Cumulative functions:
Cumulative sum: [ 1  3  6 10 15 21 28 36 45 55]
Cumulative product: [  1   2   6  24 120]


## Broadcasting


In [57]:
# Broadcasting
print("Broadcasting Examples:")

# Scalar + array
arr = np.array([1, 2, 3, 4])
print("Array:", arr)
print("Array + 5:", arr + 5)

# Different shape operations
print("\nDifferent shape operations:")
matrix = np.array([[1, 2, 3], [4, 5, 6]])
vector = np.array([10, 20, 30])

print("Matrix shape:", matrix.shape)
print("Vector shape:", vector.shape)
print("Matrix:")
print(matrix)
print("Vector:", vector)
print("Matrix + Vector (broadcasting):")
print(matrix + vector)

# Using np.newaxis and np.expand_dims
print("\nUsing np.newaxis and np.expand_dims:")
arr_1d = np.array([1, 2, 3])
print("1D array:", arr_1d)
print("Shape:", arr_1d.shape)

# Add new axis
arr_2d_newaxis = arr_1d[np.newaxis, :]
print("With np.newaxis:", arr_2d_newaxis)
print("Shape:", arr_2d_newaxis.shape)

# Using expand_dims
arr_2d_expand = np.expand_dims(arr_1d, axis=0)
print("With expand_dims:", arr_2d_expand)
print("Shape:", arr_2d_expand.shape)

# Broadcasting rules example
print("\nBroadcasting rules example:")
A = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
B = np.array([10, 20, 30])             # Shape: (3,)
print("A shape:", A.shape)
print("B shape:", B.shape)
print("A + B (broadcasting):")
print(A + B)

# More complex broadcasting
print("\nMore complex broadcasting:")
C = np.array([[1], [2]])  # Shape: (2, 1)
D = np.array([10, 20, 30])  # Shape: (3,)
print("C shape:", C.shape)
print("D shape:", D.shape)
print("C + D (broadcasting):")
print(C + D)


Broadcasting Examples:
Array: [1 2 3 4]
Array + 5: [6 7 8 9]

Different shape operations:
Matrix shape: (2, 3)
Vector shape: (3,)
Matrix:
[[1 2 3]
 [4 5 6]]
Vector: [10 20 30]
Matrix + Vector (broadcasting):
[[11 22 33]
 [14 25 36]]

Using np.newaxis and np.expand_dims:
1D array: [1 2 3]
Shape: (3,)
With np.newaxis: [[1 2 3]]
Shape: (1, 3)
With expand_dims: [[1 2 3]]
Shape: (1, 3)

Broadcasting rules example:
A shape: (2, 3)
B shape: (3,)
A + B (broadcasting):
[[11 22 33]
 [14 25 36]]

More complex broadcasting:
C shape: (2, 1)
D shape: (3,)
C + D (broadcasting):
[[11 21 31]
 [12 22 32]]


## Set Operations


In [58]:
# Set Operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

print("Array 1:", arr1)
print("Array 2:", arr2)

# Union (unique elements from both arrays)
union_result = np.union1d(arr1, arr2)
print("\nUnion (unique elements from both):", union_result)

# Intersection (common elements)
intersection_result = np.intersect1d(arr1, arr2)
print("Intersection (common elements):", intersection_result)

# Set difference (elements in arr1 but not in arr2)
diff_result = np.setdiff1d(arr1, arr2)
print("Set difference (arr1 - arr2):", diff_result)

# Symmetric difference (elements in either array but not in both)
symmetric_diff = np.setxor1d(arr1, arr2)
print("Symmetric difference:", symmetric_diff)

# Check membership
print("\nMembership operations:")
test_elements = np.array([2, 6, 3])
print("Test elements:", test_elements)
print("Are elements in arr1?", np.isin(test_elements, arr1))
print("Are elements in arr2?", np.isin(test_elements, arr2))

# Using in1d (deprecated but still works)
print("Using in1d (deprecated):", np.in1d(test_elements, arr1))


Array 1: [1 2 3 4 5]
Array 2: [3 4 5 6 7]

Union (unique elements from both): [1 2 3 4 5 6 7]
Intersection (common elements): [3 4 5]
Set difference (arr1 - arr2): [1 2]
Symmetric difference: [1 2 6 7]

Membership operations:
Test elements: [2 6 3]
Are elements in arr1? [ True False  True]
Are elements in arr2? [False  True  True]
Using in1d (deprecated): [ True False  True]


C:\Users\Sumit Amit\AppData\Local\Temp\ipykernel_6696\689186546.py:32: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  print("Using in1d (deprecated):", np.in1d(test_elements, arr1))


## Fourier Transforms


In [59]:
# Fourier Transforms
# 1D FFT
signal = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("Original signal:", signal)

# Forward FFT
fft_result = np.fft.fft(signal)
print("\nFFT result:", fft_result)

# Inverse FFT
ifft_result = np.fft.ifft(fft_result)
print("Inverse FFT (should recover original):", ifft_result.real)

# 2D FFT
print("\n2D FFT example:")
image = np.array([[1, 2], [3, 4]])
print("2D array:")
print(image)

fft2_result = np.fft.fft2(image)
print("2D FFT result:")
print(fft2_result)

ifft2_result = np.fft.ifft2(fft2_result)
print("2D Inverse FFT:")
print(ifft2_result.real)

# N-dimensional FFT
print("\nN-dimensional FFT:")
nd_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D array shape:", nd_array.shape)

fftn_result = np.fft.fftn(nd_array)
print("N-dimensional FFT shape:", fftn_result.shape)

ifftn_result = np.fft.ifftn(fftn_result)
print("N-dimensional Inverse FFT shape:", ifftn_result.shape)


Original signal: [1 2 3 4 5 6 7 8]

FFT result: [36.+0.j         -4.+9.65685425j -4.+4.j         -4.+1.65685425j
 -4.+0.j         -4.-1.65685425j -4.-4.j         -4.-9.65685425j]
Inverse FFT (should recover original): [1. 2. 3. 4. 5. 6. 7. 8.]

2D FFT example:
2D array:
[[1 2]
 [3 4]]
2D FFT result:
[[10.+0.j -2.+0.j]
 [-4.+0.j  0.+0.j]]
2D Inverse FFT:
[[1. 2.]
 [3. 4.]]

N-dimensional FFT:
3D array shape: (2, 2, 2)
N-dimensional FFT shape: (2, 2, 2)
N-dimensional Inverse FFT shape: (2, 2, 2)


## Polynomials


In [60]:
# Polynomials
# Create polynomial: 2x^2 + 3x + 1
coeffs = np.array([2, 3, 1])  # coefficients from highest to lowest degree
print("Polynomial coefficients:", coeffs)
print("Represents: 2x^2 + 3x + 1")

# Create polynomial object
poly = np.poly1d(coeffs)
print("\nPolynomial object:", poly)

# Evaluate polynomial at specific points
x_values = np.array([0, 1, 2, 3])
y_values = np.polyval(coeffs, x_values)
print("\nEvaluating polynomial at x =", x_values)
print("y values:", y_values)

# Polynomial fitting (find best fit polynomial)
print("\nPolynomial fitting:")
# Generate some noisy data
x_data = np.linspace(0, 4, 20)
y_data = 2*x_data**2 + 3*x_data + 1 + 0.5*np.random.randn(20)

# Fit polynomial of degree 2
fitted_coeffs = np.polyfit(x_data, y_data, 2)
print("Fitted coefficients:", fitted_coeffs)
print("Original coefficients:", coeffs)

# Find roots of polynomial
print("\nFinding roots:")
roots = np.roots(coeffs)
print("Roots of 2x^2 + 3x + 1:", roots)

# Verify roots by evaluating polynomial
print("Verification (should be close to 0):")
for root in roots:
    value = np.polyval(coeffs, root)
    print(f"P({root:.3f}) = {value:.6f}")

# Polynomial operations
print("\nPolynomial operations:")
p1 = np.poly1d([1, 2, 3])  # x^2 + 2x + 3
p2 = np.poly1d([1, 1])     # x + 1

print("p1:", p1)
print("p2:", p2)
print("p1 + p2:", p1 + p2)
print("p1 * p2:", p1 * p2)
print("p1 / p2:", p1 / p2)


Polynomial coefficients: [2 3 1]
Represents: 2x^2 + 3x + 1

Polynomial object:    2
2 x + 3 x + 1

Evaluating polynomial at x = [0 1 2 3]
y values: [ 1  6 15 28]

Polynomial fitting:
Fitted coefficients: [2.11840748 2.44500293 1.69455424]
Original coefficients: [2 3 1]

Finding roots:
Roots of 2x^2 + 3x + 1: [-1.  -0.5]
Verification (should be close to 0):
P(-1.000) = 0.000000
P(-0.500) = 0.000000

Polynomial operations:
p1:    2
1 x + 2 x + 3
p2:  
1 x + 1
p1 + p2:    2
1 x + 3 x + 4
p1 * p2:    3     2
1 x + 3 x + 5 x + 3
p1 / p2: (poly1d([1., 1.]), poly1d([2.]))
